### ISSUE TITLE
End of 2023 roadmap

### ISSUE THREAD

**Issue by dsherret** [dprint/dprint#769]
Goal is to make dprint work in more places and improve dprint-plugin-prettier:

- [x] https://github.com/dprint/dprint/issues/659
- [x] https://github.com/dprint/dprint/issues/738
- [ ] https://github.com/dprint/dprint/issues/761 and other issues
- dprint-plugin-prettier
   - [ ] Prettier plugin should work on more architectures (https://github.com/dprint/dprint-plugin-prettier/issues/60)
   - [x] https://github.com/dprint/dprint-plugin-prettier/pull/62
   - [ ] https://github.com/dprint/dprint-plugin-prettier/issues/55
   - [x] https://github.com/dprint/dprint-plugin-prettier/pull/70
- dprint-plugin-roslyn
   - [x] mac aarch64 issues
      - https://github.com/dprint/dprint-plugin-roslyn/issues/12
      - https://github.com/dprint/dprint-plugin-roslyn/issues/8
   - [x] Add linux musl builds for dprint-plugin-roslyn https://github.com/dprint/dprint-plugin-roslyn/pull/15
- [ ] Range formatting for Wasm plugins

Additional plugins:

- [x] https://github.com/astral-sh/ruff (Done: https://dprint.dev/plugins/ruff)
- [x] https://github.com/biomejs/biome/tree/main/crates/biome_formatter (Done: https://dprint.dev/plugins/biome)
- [x] dprint-plugin-jupyter - https://dprint.dev/plugins/jupyter/ 

Infrastructure:

- [x] https://github.com/dprint/automation/issues/2
  - [x]  typescript
  - [x] Biome
  - [x] Ruff
  - [x] json
  - [x] dockerfile
  - [x] markdown
  - [x] jupyter
  - [x] roslyn
  - [x] exec
  - [x] toml

**Comment by doox911-opensource** [comment]
So, when should we wait for the dprint-vue-plugin?)
